WebProject/WebProject/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProject.Services.Contracts.ControllerServices;
using WebProject.Services.Contracts.Model.DTOs;
using WebProject.Services.Contracts.Model.Enums;
using WebProject.Services.Contracts.Model.ViewModels;

namespace WebProject.Controllers
{
    [RoutePrefix("Courses")]
    public class CourseController : BaseController
    {
        private ICourseControllerService _courseService;

        public CourseController(ICourseControllerService courseService)
        {
            _courseService = courseService;
        }

        [HttpGet]
        [Route("~/")]
        public ActionResult Index()
        {
            var courses = _courseService.GetAll();
            return View(courses);
        }

        [HttpGet]
        [HandleError]
        [Route("Course/{courseId}")]
        public ActionResult GetById(Guid courseId)
        {
            try
            {
                var course = _courseService.GetById(courseId);
                if (User != null && User.IsInRole("Trainer"))
                {
                    foreach (var trainerCourseDto in course.TrainerCourses.Where(x => x.Trainer.UserId == User.Id))
                    {
                        trainerCourseDto.Course.IsCanEdit = true;
                    }
                }

                return View(course);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpGet]
        [Route("Edit/{courseId}")]
        [Authorize(Roles = nameof(RoleType.Admin) + "," + nameof(RoleType.Trainer))]
        public ActionResult EditCourse(Guid? courseId)
        {
            try
            {
                ViewBag.Trainers = AutoMapper.Mapper.Map<IEnumerable<TrainerDTO>, IEnumerable<TrainerShortInfo>>(_courseService.GetTrainerShortInfos());
                var course = _courseService.GetById(courseId.Value);
                ViewBag.CourseGroup = _courseService.GetCourseGroup();
                foreach (var trainerCourse in course.TrainerCourses)
                {
                    course.TrainerCourseGuids.Add(trainerCourse.TrainerId);
                }
                return View(course);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpPost]
        [Route("Edit/{courseId}")]
        [Authorize(Roles = nameof(RoleType.Admin) + "," + nameof(RoleType.Trainer))]
        public ActionResult EditCourse(CourseDTO course)
        {
            ViewBag.CourseGroup = _courseService.GetCourseGroup();
            ViewBag.Trainers = AutoMapper.Mapper.Map<IEnumerable<TrainerDTO>, IEnumerable<TrainerShortInfo>>(_courseService.GetTrainerShortInfos());

            CheckValidation(course, false);

            if (ModelState.IsValid)
            {
                _courseService.Update(course);
                return RedirectToAction("Index");
            }

            return View(course);
        }

        [HttpGet]
        [Route("Add")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult AddCourse()
        {
            ViewBag.Trainers = AutoMapper.Mapper.Map<IEnumerable<TrainerDTO>, IEnumerable<TrainerShortInfo>>(_courseService.GetTrainerShortInfos());
            ViewBag.CourseGroup = _courseService.GetCourseGroup();
            return View("AddCourse");
        }

        [HttpPost]
        [Route("Add")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult AddCourse(CourseDTO course)
        {
            CheckValidation(course, true);
            if (ModelState.IsValid)
            {
                course.CourseId = Guid.NewGuid();
                _courseService.Add(course);
                return RedirectToAction("Index");
            }
            ViewBag.CourseGroup = _courseService.GetCourseGroup();
            ViewBag.Trainers = AutoMapper.Mapper.Map<IEnumerable<TrainerDTO>, IEnumerable<TrainerShortInfo>>(_courseService.GetTrainerShortInfos());
            return View(course);
        }
        
        [Route("Delete/{courseId}")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult DeleteCourse(Guid courseId)
        {
            try
            {
                _courseService.Delete(_courseService.GetById(courseId));
                return RedirectToAction("Index");
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        public ActionResult MyCourses()
        {
            return View(_courseService.GetMyCourses(User.Id));
        }

        private void CheckValidation(CourseDTO course, bool isAdd)
        {
            if (string.IsNullOrEmpty(course.CourseName))
            {
                ModelState.AddModelError("CourseName", "Course Name is required");
            }

            if (isAdd == false && course.FormatedStartDate == null)
            {
                ModelState.AddModelError("FormatedStartDate", "Start Date is required");
            }

            if (isAdd== true && course.StartDate == null)
            {
                ModelState.AddModelError("StartDate", "Start Date is required");
            }

            if (course.TrainerCourseGuids.Count == 0)
            {
                ModelState.AddModelError("TrainerCourseGuids", "Choose trainer");
            }

            if (course.Description == null)
            {
                ModelState.AddModelError("Description", "Add description");
            }
        }
    }
}

WebProject/WebProject/Views/Course/AddCourse.cshtml
@model WebProject.Services.Contracts.Model.DTOs.CourseDTO

@{
    ViewBag.Title = "AddCourse";
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    using (Html.BeginForm("AddCourse", "Course", FormMethod.Post))
     {
         <h2>Add Course</h2>
         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.CourseName, "Course name", htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     @Html.EditorFor(model => model.CourseName, new {htmlAttributes = new {@class = "form-control"}})
                     @Html.ValidationMessageFor(model => model.CourseName)
                 </div>
             </div>
         </div>

         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                     @Html.ValidationMessageFor(model => model.Description)
                 </div>
             </div>
         </div>

         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.StartDate, htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control", @type = "date"}})
                     @Html.ValidationMessageFor(model => model.StartDate)
                 </div>
             </div>
         </div>

         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.CourseGroupId, "Course group", htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     @Html.DropDownListFor(model => model.CourseGroupId, new SelectList(ViewBag.CourseGroup, "CourseGroupId", "Description"), new {@class = "form-control"})
                 </div>
             </div>
         </div>

         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.CourseTypeId, "Course type", htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     <select class="select form-control" id="CourseTypeId" name="CourseTypeId">
                         <option value="1">Practical</option>
                         <option value="2">Lectures</option>
                     </select>
                 </div>
             </div>
         </div>

         <div class="form-group">
             <div class="row">
                 @Html.LabelFor(model => model.TrainerCourseGuids, "Trainer", htmlAttributes: new {@class = "control-label col-md-2"})
                 <div class="col-md-6">
                     @Html.ListBoxFor(model => model.TrainerCourseGuids, new MultiSelectList(ViewBag.Trainers, "TrainerId", "FullName"), new {@class = "form-control"})
                     @Html.ValidationMessageFor(model => model.TrainerCourseGuids)
                 </div>
             </div>
         </div>
         <div class="row resultButton">
             <input type="submit" id="confirm" class="form-control-btn btn btn-success">
             <a href="@Url.Action("Index", "Course")" class="form-control-btn btn btn-primary">Cancel</a>
         </div>
     }
}

WebProject/WebProject/Views/Course/EditCourse.cshtml
@model WebProject.Services.Contracts.Model.DTOs.CourseDTO

@{
    ViewBag.Title = "EditCourse";
}
@if (User.Identity.IsAuthenticated)
{
    using (Html.BeginForm("EditCourse", "Course", FormMethod.Post))
    {
        <h2>Edit</h2>
        @Html.HiddenFor(model => model.CourseId)
        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.CourseName, "Course name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CourseName)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.FormatedStartDate, "Start date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.FormatedStartDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(model => model.FormatedStartDate)
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.CourseGroupId, "Course group", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.CourseGroupId, new SelectList(ViewBag.CourseGroup, "CourseGroupId", "Description"), new { @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                @Html.LabelFor(model => model.CourseTypeId, "Course type", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <select class="select form-control" id="CourseTypeId" name="CourseTypeId">
                        <option value="1">Practical</option>
                        <option value="2">Lectures</option>
                    </select>
                </div>
            </div>
        </div>
        if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                <div class="row">
                    @Html.LabelFor(model => model.TrainerCourseGuids, "Trainer", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.ListBoxFor(model => model.TrainerCourseGuids, new MultiSelectList(ViewBag.Trainers, "TrainerId", "FullName", @Model.TrainerCourseGuids), new {@class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TrainerCourseGuids)
                    </div>
                </div>
            </div>
        }
        else
        {
            @Html.HiddenFor(model => model.TrainerCourseGuids)
        }
        <div class="row resultButton">
            <input type="submit" id="confirm" class="form-control-btn btn btn-success">
            <a href="@Url.Action("Index", "Course")" class="form-control-btn btn btn-primary">Cancel</a>
        </div>
    }
}

WebProject/WebProject/Views/Course/GetById.cshtml
@model WebProject.Services.Contracts.Model.DTOs.CourseDTO

@{
    ViewBag.Title = "GetById";
}

<div class="col-9">
    <h5 class="card-title">@Html.DisplayFor(model => model.CourseName)</h5>
    <p class="card-text">
        Course Group:@Html.DisplayFor(model => model.CourseGroup.Description)<br>
        Description: @Html.DisplayFor(model => model.Description)<br>
        Start date: @Html.DisplayFor(model => model.FormatedStartDate)<br>
        End date: @Html.DisplayFor(model => model.FormatedEndDate)<br>
        Trainers: @foreach (var trainer in Model.TrainerCourses.Where(x => x.EndDate == null))
        {
            @trainer.Trainer.User.FullName<br>
        }
    </p>
    <a href="@Url.Action("Index", "Course")" class="btn btn-primary">Go back</a>
    @if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("Admin"))
        {
            <a href="@Url.Action("DeleteCourse", "Course", new {courseId = Model.CourseId})" class="btn btn-danger">Delete</a>
        }
        if (User.IsInRole("Admin") || (User.IsInRole("Trainer") && Model.IsCanEdit))
        {
            <a href="@Url.Action("EditCourse", "Course",  new {courseId = Model.CourseId})" class="btn btn-warning">Edit</a>
        }
    }
</div>

WebProject/WebProject/Views/Course/Index.cshtml
@model IEnumerable<WebProject.Services.Contracts.Model.DTOs.CourseDTO>


@{
    ViewBag.Title = "AllCourses";
}

@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("Admin"))
    {
        <a href="@Url.Action("AddCourse", "Course")" class="btn btn-info button">Add course</a>
    }
    if(User.IsInRole("Trainer"))
    {
    <a href="@Url.Action("MyCourses", "Course")" class="btn btn-info button">My courses</a>
    }
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Start date</th>
            <th>End date</th>
            <th>Course group</th>
            <th>Trainers</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CourseName</td>
                <td>@item.FormatedStartDate</td>
                <td>@item.FormatedEndDate</td>
                <td>@item.CourseGroup.Description</td>
                <td>
                    @foreach (var trainer in item.TrainerCourses.Where(x => x.EndDate == null))
                    {
                        @trainer.Trainer.User.FullName<br>
                    }
                <td>
                    <a href=@Url.Action("GetById","Course", new{courseId = item.CourseId})>Show description</a>
                </td>
            </tr>

        }
    </tbody>
</table>

WebProject/WebProject/Views/Course/MyCourses.cshtml
@model IEnumerable<WebProject.Services.Contracts.Model.DTOs.CourseDTO>


@{
    ViewBag.Title = "MyCourses";
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Trainer"))
{
    <a href="@Url.Action("Index", "Course")" class="btn btn-primary">Go back</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Course group</th>
                <th>Trainers</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CourseName</td>
                    <td>@item.FormatedStartDate</td>
                    <td>@item.FormatedEndDate</td>
                    <td>@item.CourseGroup.Description</td>
                    <td>
                        @foreach (var trainer in item.TrainerCourses.Where(x => x.EndDate == null))
                        {
                            @trainer.Trainer.User.FullName<br>
                        }
                    <td>
                        <a href=@Url.Action("GetById","Course", new{courseId = item.CourseId})>Show description</a>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}