WebProject/WebProject/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebProject.Services.Contracts.ControllerServices;
using WebProject.Services.Contracts.Model.DTOs;
using WebProject.Services.Contracts.Model.Enums;
using WebProject.Services.Contracts.Model.InputModels;
using WebProject.Services.Contracts.Model.ViewModels;

namespace WebProject.Controllers
{
    [RoutePrefix("Trainers")]
    public class TrainerController : BaseController
    {
        private ITrainerControllerService _trainerService;

        public TrainerController(ITrainerControllerService trainerService)
        {
            _trainerService = trainerService;
        }

        [HttpGet]
        [Route()]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("Trainer/{id}")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult GetTrainerById()
        {
                return View();
        }

        [HttpGet]
        [Route("Add")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult AddTrainer()
        {
            return View();
        }

        [HttpGet]
        [Route("Edit/{id}")]
        [Authorize(Roles = nameof(RoleType.Admin) + "," + nameof(RoleType.Trainer))]
        public ActionResult EditTrainer()
        {
            return View();
        }

        [HttpGet]
        [Route("GetTrainerGroups")]
        [Authorize]
        public JsonResult GetTrainerGroups()
        {
            IList<TrainerGroupDTO> trainerGroups = new List<TrainerGroupDTO>(_trainerService.GetTrainerGroups());

            return Json(new { trainerGroups }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("HomePage")]
        [Authorize(Roles = nameof(RoleType.Trainer))]
        public ActionResult GetHomePage()
        {
            var trainer = _trainerService.GetTrainerByUserId(User.Id);
            return View(trainer);
        }
    }
}

WebProject/WebProject/Views/Trainer/AddTrainer.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <h2>Add Trainer</h2>

    <div class="form-group">
        <div class="row">
            <select class="select form-control" id="userSelect"></select>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <select class="select form-control" id="trainerGroupSelect"></select>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <input type="date" class="form-control" id="startDate" placeholder="StartDate:" aria-label="StartDate">
            <div class="invalid-feedback">
                Please enter Start Date.
            </div>
        </div>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="trainerInfo" placeholder="TrainerInfo:" aria-label="TrainerInfo">
        <div class="invalid-feedback">
            Please enter trainer info.
        </div>
    </div>
    <div class="row resultButton">
        <button type="submit" id="confirm" class="form-control-btn btn btn-success">Confirm</button>
        <a href="@Url.Action("Index", "Trainer")" class="form-control-btn btn btn-primary">Cancel</a>
    </div>

    @section Scripts {
        @Scripts.Render("~/Scripts/CustromScripts/TrainerScripts/AddTrainer.js")
    }
}

WebProject/WebProject/Views/Trainer/EditTrainer.cshtml
@{
    ViewBag.Title = "EditTrainer";
}
@if (User.Identity.IsAuthenticated)
{
    <h2>Edit trainer</h2>

    <input id="userId" type="hidden" />
    <input id="trainerId" type="hidden" />
    <input id="endDate" type="hidden" />
    <div class="form-group">
        <input type="text" class="form-control" id="trainerInfo" placeholder="TrainerInfo:" aria-label="TrainerInfo">
        <div class="invalid-feedback">
            Please enter trainer info.
        </div>
    </div>
    if (User.IsInRole("Admin"))
    {
        <div class="form-group">
            <div class="row">
                <select class="select form-control" id="trainerGroupSelect"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <input type="date" class="form-control" id="startDate" placeholder="StartDate:" aria-label="StartDate">
                <div class="invalid-feedback">
                    Please enter start date.
                </div>
            </div>
        </div>
    }
    else
    {
        <input id="trainerGroupSelect" type="hidden"/>
        <input id="startDate" type="hidden"/>
    }
        <div class="row resultButton">
            @if (User.IsInRole("Admin"))
            {
                <button type="submit" id="confirm" isAdmin="true" class="form-control-btn btn btn-success">Confirm</button>
                <a href="@Url.Action("Index", "Trainer")" class="form-control-btn btn btn-primary">Cancel</a>
            }
            else
            {
                <button type="submit" id="confirm" isAdmin="false" class="form-control-btn btn btn-success">Confirm</button>
                <a href="@Url.Action("HomePage", "Trainers")" class="form-control-btn btn btn-primary">Cancel</a>
            }
        </div>

    @section Scripts {
        @Scripts.Render("~/Scripts/CustromScripts/TrainerScripts/EditTrainer.js")
    }
}

WebProject/WebProject/Views/Trainer/GetHomePage.cshtml
@{
    ViewBag.Title = "Trainer";
}
@model WebProject.Services.Contracts.Model.DTOs.TrainerDTO

@using (Html.BeginForm("GetTrainerById", "Trainer"))
{
    <div class="row">
        <div class="col-3">
            @Html.Raw("<img style='width:80px; height:60px;' src=\"data:image/jpeg;base64,"
                      + Convert.ToBase64String(Model.User.Photo) + "\" />")
        </div>
        <div class="col-9">
            <h5 class="card-title">@Html.DisplayFor(model => model.User.FullName)</h5>
            <p class="card-text">
            <p>Email:@Html.DisplayFor(model => model.User.Email)<br></p>
            <p>Location: @Html.DisplayFor(model => model.User.Location)<br></p>
            <p>Trainer info: @Html.DisplayFor(model => model.TrainerInfo)<br></p>
            </p>
            <a href="@Url.Action("Edit", "Trainers", new{id = Model.TrainerId})" class="btn btn-warning">Edit</a>
        </div>
    </div>

}

@section Scripts {
    @Scripts.Render("~/Scripts/CustromScripts/TrainerScripts/TrainerById.js")
}

WebProject/WebProject/Views/Trainer/GetTrainerById.cshtml
@{
    ViewBag.Title = "Trainer";
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="row">
        <div class="col-3" id="photo">
            <img id="ItemPreview" src="" />
        </div>
        <div class="col-9">
            <h5 class="card-title" id="title"></h5>
            <p class="card-text" id="cardText">
            </p>
            <button type="button" class="btn btn-primary" id="goBack">Go back</button>
            <button type="button" class="btn btn-danger" id="delete">Delete</button>
            <button type="button" class="btn btn-warning" id="edit">Edit</button>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/Scripts/CustromScripts/TrainerScripts/TrainerById.js")
    }
}

WebProject/WebProject/Views/Trainer/Index.cshtml
@{
    ViewBag.Title = "Trainer Page";
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <button type="button" class="btn btn-primary" id="addUser">Add trainer</button>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Trainer Group</th>
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="trainers" id="trainers"></tbody>
    </table>
    @section Scripts {
        @Scripts.Render("~/Scripts/CustromScripts/TrainerScripts/Index.js")
    }
}