WebProject/WebProject/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Security;
using WebProject.Services.Contracts.ControllerServices;
using WebProject.Services.Contracts.Model.DTOs;
using WebProject.Services.Contracts.Model.Enums;
using WebProject.Services.Contracts.Model.InputModels;
using WebProject.Services.Contracts.Model.ViewModels;
namespace WebProject.Controllers
{
    [RoutePrefix("Users")]
    public class UserController : BaseController
    {
        private IUserControllerService _userService;

        public UserController(IUserControllerService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        [Route()]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult Index()
        {
            var users = _userService.GetAll();
            return View(users);
        }

        [HttpGet]
        [Route("User/{id}")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult GetUserById(string id)
        {
            try
            {
                var user = _userService.GetById(new Guid(id));
                return View(user);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpPost]
        [Route("Delete")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult DeleteUser(string userId)
        {
            try
            {
                _userService.Delete(_userService.GetById(new Guid(userId)));
                return RedirectToAction("Index");
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpGet]
        [Route("Add")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult AddUser()
        {
            return View("AddUser");
        }

        [HttpPost]
        [Route("Add")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public Guid AddUser(UserModel user)
        {
            user.UserId = Guid.NewGuid();
            _userService.Add(AutoMapper.Mapper.Map<UserModel, UserDTO>(user));
            return user.UserId;
        }

        [HttpGet]
        [Route("Edit/{id}")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult EditUser(string id)
        {
            try
            {
                var user = _userService.GetById(new Guid(id));
                return View(user);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error404", "Error");
            }
        }

        [HttpPost]
        [Route("Edit")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public ActionResult EditUser(UserModel user)
        {
            _userService.Update(AutoMapper.Mapper.Map<UserModel, UserDTO>(user));
            return View(AutoMapper.Mapper.Map<UserModel, UserDTO>(user));
        }

        [HttpPost]
        [Route("LoadPhoto")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public void LoadPhoto(FormCollection data)
        {
            var user = _userService.GetById(new Guid(data["userId"]));
            var value = Request.Files["photo"];
            if (Request.Files["photo"] != null)
            {
                using (var binaryReader = new BinaryReader(Request.Files["photo"].InputStream))
                {
                    var imagefile = binaryReader.ReadBytes(Request.Files["photo"].ContentLength);
                    user.Photo = imagefile;
                }
            }
            _userService.Update(user);
        }

        [Route("GetUserList")]
        [Authorize(Roles = nameof(RoleType.Admin))]
        public JsonResult GetUserList()
        {
            IList<UserShortInfoModel> usersShortInfo = new List<UserShortInfoModel>(AutoMapper.Mapper.Map<IEnumerable<UserDTO>, IEnumerable<UserShortInfoModel>>(_userService.GetAll().Where(x => x.IsDelete == false)));

            return Json(new { usersShortInfo }, JsonRequestBehavior.AllowGet);
        }

        [Route("Login")]
        public ActionResult LoginUser()
        {
            return View();
        }

        [HttpPost]
        [Route("Login")]
        public ActionResult LoginUser(LoginUserModel loginModel)
        {
            try
            {
                var user = _userService.Login(loginModel);

                CustomPrincipalSerializeModel serializeModel = new CustomPrincipalSerializeModel
                {
                    Id = user.UserId,
                    FullName = user.FullName,
                    Role = Enum.GetName(typeof(RoleType), user.Role)
                };

                JavaScriptSerializer serializer = new JavaScriptSerializer();
                var userData = serializer.Serialize(serializeModel);

                FormsAuthenticationTicket authTicket = new FormsAuthenticationTicket(
                    1,
                    user.Login,
                    DateTime.Now,
                    DateTime.Now.AddMinutes(15),
                    false,
                    userData);
                string encTicket = FormsAuthentication.Encrypt(authTicket);
                HttpCookie faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
                Response.Cookies.Add(faCookie);

                return RedirectToAction("Index","Course");
            }
            catch (ArgumentNullException ex)
            {
                ModelState.AddModelError(ex.ParamName, ex.Message);

                return View(loginModel);
            }
        }

        [HttpGet]
        [Route("Logout")]
        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);
            
            SessionStateSection sessionStateSection = (SessionStateSection)WebConfigurationManager.GetSection("system.web/sessionState");
            HttpCookie cookie2 = new HttpCookie(sessionStateSection.CookieName, "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);

            return RedirectToAction("Index", "Course");
        }
    }
}

WebProject/WebProject/Views/Shared/Error404.cshtml
<!-- Google font -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

<div id="notfound">
    <div class="notfound">
        <div class="notfound-404">
            <h1>Oops!</h1>
        </div>
        <h2>404 - Page not found</h2>
        <p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
    </div>
</div>

WebProject/WebProject/Views/Shared/_Layout.cshtml
@using WebProject.Services.CustomPrincipal
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body id="main_div">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Users centre", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
                    @Html.ActionLink("Trainers centre", "", "Trainers", new { area = "" }, new { @class = "navbar-brand" })
                }
                if (User.IsInRole("Trainer"))
                {
                    @Html.ActionLink("Home page", "HomePage", "Trainers", new { area = "" }, new { @class = "navbar-brand" })
                }
            }

            @Html.ActionLink("Courses", "Index", "Course", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        @if (User.Identity.IsAuthenticated)
        {
        <div class="auth">
            <h4 class="name navbar-brand">@((User as CustomPrincipal).FullName)</h4>
            @Html.ActionLink("Logout", "Logout", "Users", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        }
        else
        {
            @Html.ActionLink("Login", "Login", "Users", new { area = "" }, new { @class = "navbar-brand auth" })
        }
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "User")</li>
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>
</body>
@Scripts.Render("~/Scripts/CustromScripts/UserScripts/Constants.js")
</html>